/*
 * generated by Xtext 2.29.0
 */
package edu.vanderbilt.isis.caid.assurancedsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class AssuranceWebModule extends AbstractAssuranceWebModule {
}
