/*
 * generated by Xtext 2.29.0
 */
package edu.vanderbilt.isis.caid.assurancedsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.vanderbilt.isis.caid.assurancedsl.AssuranceRuntimeModule;
import edu.vanderbilt.isis.caid.assurancedsl.AssuranceStandaloneSetup;
import edu.vanderbilt.isis.caid.assurancedsl.ide.AssuranceIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class AssuranceWebSetup extends AssuranceStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AssuranceRuntimeModule(), new AssuranceIdeModule(), new AssuranceWebModule()));
	}
	
}
