/*
 * generated by Xtext 2.29.0
 */
package edu.vanderbilt.isis.caid.assurancedsl.tests

import com.google.inject.Inject
import edu.vanderbilt.isis.caid.assurancedsl.assurance.AssuranceModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AssuranceInjectorProvider)
class AssuranceParsingTest {
	@Inject
	ParseHelper<AssuranceModel> parseHelper
	
	@Test
	def void loadModel() {

	}
}
