const model = [
    {
        id: 'model/G1/G2/S1/A1',
        type: 'Assumption',
        summary: 'All hazards have been identified',
        name: 'A1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/C1',
        type: 'Context',
        summary: 'Operating Role and Context',
        name: 'C1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/C2',
        type: 'Context',
        summary: 'Control System Definition',
        name: 'C2',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/C3',
        type: 'Context',
        summary: 'Tolerability targets (Ref Z)',
        name: 'C3',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/C4',
        type: 'Context',
        summary: 'Hazards identified from FHA (Ref Y)',
        name: 'C4',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/C5',
        type: 'Context',
        summary: 'SIL Guidelines and Processes',
        name: 'C5',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/C6',
        type: 'Context',
        summary: 'Identified software hazards',
        name: 'C6',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1',
        type: 'Goal',
        inContextOf: ['model/G1/C1', 'model/G1/C2'],
        solvedBy: ['model/G1/G2', 'model/G1/G3'],
        summary: 'Control System is acceptably safe to operate indeed yesh',
        name: 'G1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2',
        type: 'Goal',
        inContextOf: ['model/G1/G2/C3', 'model/G1/G2/C4'],
        solvedBy: ['model/G1/G2/S1'],
        summary: 'All identified hazards have been eliminated or sufficiently mitigated',
        name: 'G2',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3',
        type: 'Goal',
        inContextOf: ['model/G1/G2/C4', 'model/G1/G3/C5'],
        solvedBy: ['model/G1/G3/S2'],
        summary: 'Software on the Control System has been developed to SIL appropriate to hazards involved',
        name: 'G3',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G4',
        type: 'Goal',
        solvedBy: ['model/G1/G2/S1/G4/Sn1'],
        summary: 'Hazard H1 has been eliminated',
        name: 'G4',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G5',
        type: 'Goal',
        solvedBy: ['model/G1/G2/S1/G5/Sn2'],
        summary: 'Probability of Hazard H2 occuring < 1x10-6 per year',
        name: 'G5',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G6',
        type: 'Goal',
        solvedBy: ['model/G1/G2/S1/G5/Sn2'],
        summary: 'Probability of Hazard H3 occuring < 1x10-3 per year',
        name: 'G6',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G7',
        type: 'Goal',
        solvedBy: ['model/G1/G3/S2/G7/Sn3'],
        summary: 'Primary Protection System Developed to SIL 4',
        name: 'G7',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G8',
        type: 'Goal',
        solvedBy: ['model/G1/G3/S2/G8/Sn4'],
        summary: 'Secondary Protection System Development to SIL 2',
        name: 'G8',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/J1',
        type: 'Justification',
        summary: 'SIL apportionment is correct and complete',
        name: 'J1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G4/Sn1',
        type: 'Solution',
        summary: 'Formal Verification',
        name: 'Sn1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G5/Sn2',
        type: 'Solution',
        summary: 'Fault Tree Analysis',
        name: 'Sn2',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G7/Sn3',
        type: 'Solution',
        summary: 'Process Evidence for SIL 4',
        name: 'Sn3',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G8/Sn4',
        type: 'Solution',
        summary: 'Process Evidence for SIL 2',
        name: 'Sn4',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1',
        type: 'Strategy',
        inContextOf: ['model/G1/G2/S1/A1'],
        solvedBy: ['model/G1/G2/S1/G4', 'model/G1/G2/S1/G5', 'model/G1/G2/S1/G6'],
        summary: 'Argument over each indentified hazard',
        name: 'S1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2',
        type: 'Strategy',
        inContextOf: ['model/G1/G3/S2/C6', 'model/G1/G3/S2/J1'],
        solvedBy: ['model/G1/G3/S2/G7', 'model/G1/G3/S2/G8'],
        summary: 'Argument over all allocated SIL for Primary and Secondary elements',
        name: 'S2',
        namespace: 'model',
        info: '',
    },
];

export default model;
