const longTexts = [
    {
        id: 'model/G1/G2/S1/A1',
        type: 'Assumption',
        summary: 'All hazards have been identified',
        name: 'A1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/C1',
        type: 'Context',
        summary: '',
        name: 'C1',
        namespace: 'model',
        info: "What is Lorem Ipsum?\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n\nWhere does it come from?\nContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\n\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.\n\nWhere can I get some?\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
        labels: ['laban'],
    },
    {
        id: 'model/G1/C2NEW_NAME_VERY_VERY_LONGC2NEW_NAME_VERY_VERY_LONGC2NEW_NAME_VERY_VERY_LONG',
        type: 'Context',
        summary: 'Control System Definition',
        name: 'C2NEW_NAME_VERY_VERY_LONGC2NEW_NAME_VERY_VERY_LONGC2NEW_NAME_VERY_VERY_LONG',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/C3',
        type: 'Context',
        summary: 'Tolerability targets (Ref Z)',
        name: 'C3',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/C4',
        type: 'Context',
        summary: 'Hazards identified from FHA (Ref Y)',
        name: 'C4',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/C5',
        type: 'Context',
        summary: 'SIL Guidelines and Processes',
        name: 'C5',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/C6',
        type: 'Context',
        summary: 'Identified software hazards',
        name: 'C6',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1',
        type: 'Goal',
        inContextOf: [
            'model/G1/A33',
            'model/G1/A_VERY_LONG_ANNOYING_NAME_STRETCHING_THREE_LINES',
            'model/G1/C1',
            'model/G1/C2NEW_NAME_VERY_VERY_LONGC2NEW_NAME_VERY_VERY_LONGC2NEW_NAME_VERY_VERY_LONG',
        ],
        solvedBy: ['model/G1/G2', 'model/G1/G3', 'model/G1/SOLUTION_WITH_AVERYREYRHDSFHHSLSLLSLSDFDFf'],
        summary: '',
        name: 'G1',
        namespace: 'model',
        info: "What is Lorem Ipsum?\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n\nWhere does it come from?\nContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\n\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.\n\nWhere can I get some?\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    },
    {
        id: 'model/G1/G2',
        type: 'Goal',
        inContextOf: ['model/G1/G2/C3', 'model/G1/G2/C4'],
        solvedBy: ['model/G1/G2/S1'],
        summary: 'All identified hazards have been eliminated or sufficiently mitigated',
        name: 'G2',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3',
        type: 'Goal',
        inContextOf: ['model/G1/G2/C4', 'model/G1/G3/C5'],
        solvedBy: ['model/G1/G3/S2'],
        summary: 'Software on the Control System has been developed to SIL appropriate to hazards involved',
        name: 'G3',
        namespace: 'model',
        info: '',
        labels: ['laban'],
    },
    {
        id: 'model/G1/G2/S1/G4',
        type: 'Goal',
        solvedBy: ['model/G1/G2/S1/G4/Sn1'],
        summary: 'Hazard H1 has been eliminated',
        name: 'G4',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G5',
        type: 'Goal',
        solvedBy: ['model/G1/G2/S1/G5/Sn2'],
        summary: 'Probability of Hazard H2 occuring < 1x10-6 per year',
        name: 'G5',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G6',
        type: 'Goal',
        solvedBy: ['model/G1/G2/S1/G5/Sn2'],
        summary: 'Probability of Hazard H3 occuring < 1x10-3 per year',
        name: 'G6',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G7',
        type: 'Goal',
        solvedBy: ['model/G1/G3/S2/G7/Sn3'],
        summary: 'Primary Protection System Developed to SIL 4',
        name: 'G7',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G8',
        type: 'Goal',
        solvedBy: ['model/G1/G3/S2/G8/Sn4'],
        summary: 'Secondary Protection System Development to SIL 2',
        name: 'G8',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/J1',
        type: 'Justification',
        summary: 'SIL apportionment is correct and complete',
        name: 'J1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G4/Sn1',
        type: 'Solution',
        summary: 'Formal Verification',
        name: 'Sn1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1/G5/Sn2',
        type: 'Solution',
        summary: 'Fault Tree Analysis',
        name: 'Sn2',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G7/Sn3',
        type: 'Solution',
        summary: 'Process Evidence for SIL 4',
        name: 'Sn3',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2/G8/Sn4',
        type: 'Solution',
        summary: 'Process Evidence for SIL 2',
        name: 'Sn4',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G2/S1',
        type: 'Strategy',
        inContextOf: ['model/G1/G2/S1/A1'],
        solvedBy: ['model/G1/G2/S1/G4', 'model/G1/G2/S1/G5', 'model/G1/G2/S1/G6'],
        summary: 'Argument over each indentified hazard',
        name: 'S1',
        namespace: 'model',
        info: '',
    },
    {
        id: 'model/G1/G3/S2',
        type: 'Strategy',
        inContextOf: ['model/G1/G3/S2/C6', 'model/G1/G3/S2/J1'],
        solvedBy: ['model/G1/G3/S2/G7', 'model/G1/G3/S2/G8'],
        summary: '',
        name: 'S2',
        namespace: 'model',
        info: "What is Lorem Ipsum?\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n\nWhere does it come from?\nContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\n\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.\n\nWhere can I get some?\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    },
    {
        id: 'model/G1/A_VERY_LONG_ANNOYING_NAME_STRETCHING_THREE_LINES',
        type: 'Assumption',
        name: 'A_VERY_LONG_ANNOYING_NAME_STRETCHING_THREE_LINES',
        namespace: 'model',
        summary: '',
        info: 'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    },
    {
        id: 'model/G1/A33',
        type: 'Assumption',
        name: 'A33',
        namespace: 'model',
        summary: '',
    },
    {
        id: 'model/G1/SOLUTION_WITH_AVERYREYRHDSFHHSLSLLSLSDFDFf',
        type: 'Solution',
        name: 'SOLUTION_WITH_AVERYREYRHDSFHHSLSLLSLSDFDFf',
        namespace: 'model',
        summary: '',
        info: "What is Lorem Ipsum?\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\n\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n\nWhere does it come from?\nContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\n\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.\n\nWhere can I get some?\nThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
    },
];

export default longTexts;
