export const ROV_LABELS = [
    {
        name: 'RotorJammed',
        description: '',
        isGroup: false,
    },
    {
        name: 'Descending',
        description: '',
        isGroup: false,
    },
    {
        name: 'Surfacing',
        description: '',
        isGroup: false,
    },
    {
        name: 'PipeTracking',
        description: '',
        isGroup: false,
    },
    {
        name: 'LowBattery',
        description: '',
        isGroup: false,
    },
    {
        name: 'NominalModes',
        description: '',
        isGroup: true,
        parent: 'OperatingModes',
        members: ['Descending', 'PipeTracking', 'Surfacing'],
    },
    {
        name: 'FaultyModes',
        description: '',
        isGroup: true,
        parent: 'OperatingModes',
        members: ['LowBattery', 'RotorJammed'],
    },
    {
        name: 'OperatingModes',
        description: '',
        isGroup: true,
        parent: null,
        members: [],
    },
    {
        name: 'VehicleType',
        description: '',
        isGroup: true,
        parent: null,
        members: ['GROUND_ROVER', 'ROV'],
    },
    {
        name: 'GROUND_ROVER',
        description: '',
        isGroup: false,
    },
    {
        name: 'ROV',
        description: '',
        isGroup: false,
    },
];

export const ROV_MODEL = [
    {
        id: 'model/Descending',
        namespace: 'model',
        type: 'Goal',
        summary: '',
        info: '',
        name: 'Descending',
        labels: ['Descending'],
    },
    {
        id: 'model/LowBattery',
        namespace: 'model',
        type: 'Goal',
        summary: '',
        info: '',
        name: 'LowBattery',
        labels: ['LowBattery'],
    },
    {
        id: 'model/PipeTrackingROV',
        namespace: 'model',
        type: 'Goal',
        summary: '',
        info: '',
        name: 'PipeTrackingROV',
        labels: ['PipeTracking', 'ROV'],
    },
    {
        id: 'model/GROUND_ROVER',
        namespace: 'model',
        type: 'Goal',
        summary: '',
        info: '',
        name: 'GROUND_ROVER',
        labels: ['GROUND_ROVER'],
    },
    {
        id: 'model/LowBatteryDescending',
        namespace: 'model',
        type: 'Goal',
        summary: '',
        info: '',
        name: 'LowBatteryDescending',
        labels: ['LowBattery', 'Descending'],
    },
    {
        id: 'model/NoLabel',
        namespace: 'model',
        type: 'Goal',
        summary: '',
        info: '',
        name: 'NoLabel',
        labels: [],
    },
];
