/*
 * generated by Xtext 2.29.0
 */
package edu.vanderbilt.isis.caid.assurancedsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.vanderbilt.isis.caid.assurancedsl.AssuranceRuntimeModule;
import edu.vanderbilt.isis.caid.assurancedsl.AssuranceStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AssuranceIdeSetup extends AssuranceStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AssuranceRuntimeModule(), new AssuranceIdeModule()));
	}
	
}
