/*
 * generated by Xtext 2.29.0
 */
package edu.vanderbilt.isis.caid.assurancedsl.ide;
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.editor.quickfix.IQuickFixProvider;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.codeActions.QuickFixCodeActionService;
import org.eclipse.xtext.ide.server.commands.IExecutableCommandService;
import org.eclipse.xtext.ide.server.hover.HoverService;
import edu.vanderbilt.isis.caid.assurancedsl.ide.contentassist.AssuranceIdeContentProposalProvider;

/**
 * Use this class to register ide components.
 */
public class AssuranceIdeModule extends AbstractAssuranceIdeModule {
    public Class<? extends HoverService> bindHoverService() {
		return EclipseLikeHoverService.class;
	}
	
	public Class<? extends IExecutableCommandService> bindIExecutableCommandService() {
		return CommandService.class;
	}
	
	public Class<? extends IQuickFixProvider> bindIQuickFixProvider() {
		return AssuranceIdeQuickfixProvider.class;
	}
	
	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return QuickFixCodeActionService.class;
	}
	
	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return AssuranceIdeContentProposalProvider.class;
	}
}
