/*
 * generated by Xtext 2.29.0
 */
package edu.vanderbilt.isis.caid.assurancedsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AssuranceStandaloneSetup extends AssuranceStandaloneSetupGenerated {

	public static void doSetup() {
		new AssuranceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
